export {default as Header} from './header'
export {default as SpecialOffer} from './SpecialOffer'
export {default as MenuSection} from './menuSection'
export {default as AboutSection} from './About'
export {default as BookSection} from './bookSection'
export {default as FooterSection} from './footerSection'